// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFgfDNljVMIx5zYJg2AlF3mDCgzG5G6ok',
    appId: '1:775434382942:web:15629867c84cd88c6c0ecf',
    messagingSenderId: '775434382942',
    projectId: 'uber-ce008',
    authDomain: 'uber-ce008.firebaseapp.com',
    storageBucket: 'uber-ce008.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFw_-P29hgIhzSZ017-Muu8CphLdvQ8OI',
    appId: '1:775434382942:android:6f5e4e371eae176e6c0ecf',
    messagingSenderId: '775434382942',
    projectId: 'uber-ce008',
    storageBucket: 'uber-ce008.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmeNzd9nqjZOWD-oO3Kbbpad1iW7bVKhA',
    appId: '1:775434382942:ios:a7990d6bac1417e96c0ecf',
    messagingSenderId: '775434382942',
    projectId: 'uber-ce008',
    storageBucket: 'uber-ce008.firebasestorage.app',
    iosBundleId: 'com.example.primeTaxiFlutterUiKit',
  );

}